version: '3.8'

services:

    abc_electronics:
        image: sarthakbhagat/abc_electronics:sprint2
        ports:
            - 8080:8080
        depends_on:
            - postgres
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sprint2
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=password

    postgres:
        image: postgres:14.5
        ports:
            - 5432:5432

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sprint2
